spring.application.name=fincore

spring.datasource.url=jdbc:postgresql://localhost:5432/fincore
spring.datasource.username=fincore_user
spring.datasource.password=fincore_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081